"use client"

import { useState } from "react"
import { ChevronDown } from "lucide-react"
import { cn } from "@/lib/utils"

const faqs = [
  {
    question: "Is the AI Lyrics Generator free to use?",
    answer:
      "Yes! Our basic lyrics generation service is completely free. You can generate unlimited lyrics with standard features. We also offer premium plans with advanced customization options and priority generation.",
  },
  {
    question: "Are the generated lyrics original and copyright-free?",
    answer:
      "Every lyric generated by our AI is 100% original and unique. The lyrics are created specifically for you and are copyright-free, meaning you can use them for personal or commercial projects without any restrictions.",
  },
  {
    question: "What languages does the generator support?",
    answer:
      "Our AI currently supports multiple languages including English, Spanish, French, German, Italian, Portuguese, Japanese, Korean, and Chinese. You can specify your preferred language in the language field when generating lyrics.",
  },
  {
    question: "Can I edit the generated lyrics?",
    answer:
      "Yes! Once lyrics are generated, you can edit them directly in the output panel. Feel free to modify, add, or remove any lines to make the lyrics truly your own. You can also regenerate for different variations.",
  },
  {
    question: "How long does it take to generate lyrics?",
    answer:
      "Generation typically takes just 3-10 seconds depending on the length and complexity of your request. Our advanced AI models work quickly to deliver high-quality, creative lyrics almost instantly.",
  },
  {
    question: "What genres of music are supported?",
    answer:
      "We support 15+ genres including Pop, Rock, Hip Hop, R&B, Country, Jazz, Electronic, Folk, Metal, Indie, Blues, Reggae, Classical, Latin, and K-Pop. Each genre has its own unique lyrical style and patterns.",
  },
  {
    question: "Can I use the generated lyrics commercially?",
    answer:
      "Yes! All lyrics generated are yours to use however you like, including commercial use. You can use them for recording songs, performances, YouTube videos, or any other creative projects without needing to credit us.",
  },
  {
    question: "What makes your generator different from others?",
    answer:
      "Our generator uses state-of-the-art AI models that understand context, emotion, and musical structure. We offer extensive customization options, support multiple languages, and provide instant results with professional-quality output.",
  },
  {
    question: "Do I need to create an account?",
    answer:
      "No account is required to use the basic generator! You can start creating lyrics immediately. However, creating a free account allows you to save your favorite lyrics, access generation history, and unlock additional features.",
  },
  {
    question: "Can I request specific rhyme schemes or song structures?",
    answer:
      "Currently, our generator automatically determines the best rhyme scheme and structure based on your selected genre and length. We're working on adding more granular control options for advanced users in future updates.",
  },
]

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null)

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index)
  }

  return (
    <div className="max-w-3xl mx-auto">
      <h2 className="text-3xl md:text-4xl font-bold text-center mb-4 text-balance">Frequently Asked Questions</h2>
      <p className="text-center text-muted-foreground mb-12 text-pretty leading-relaxed">
        Get answers to common questions about our AI lyrics generator
      </p>

      <div className="space-y-4">
        {faqs.map((faq, index) => (
          <div key={index} className="bg-card border border-border rounded-lg overflow-hidden">
            <button
              onClick={() => toggleFAQ(index)}
              className="w-full px-6 py-4 flex items-center justify-between text-left hover:bg-muted/50 transition-colors"
              aria-expanded={openIndex === index}
            >
              <span className="font-semibold pr-8 text-pretty">{faq.question}</span>
              <ChevronDown
                className={cn("w-5 h-5 text-muted-foreground transition-transform flex-shrink-0", {
                  "transform rotate-180": openIndex === index,
                })}
              />
            </button>
            <div
              className={cn("overflow-hidden transition-all duration-300 ease-in-out", {
                "max-h-0": openIndex !== index,
                "max-h-96": openIndex === index,
              })}
            >
              <div className="px-6 pb-4 text-muted-foreground leading-relaxed text-pretty">{faq.answer}</div>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
